// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiPVelqL1hpMHclb4eHOcA3dJTdaaTQaI',
    appId: '1:445883730465:web:637601a312dca68edf3160',
    messagingSenderId: '445883730465',
    projectId: 'kazutxt-firebase-overvie-5de13',
    authDomain: 'kazutxt-firebase-overvie-5de13.firebaseapp.com',
    storageBucket: 'kazutxt-firebase-overvie-5de13.firebasestorage.app',
    measurementId: 'G-L1PDJD4LTR',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSw2n_4c4UFgZCC90H8wYPLYEoc59vlxI',
    appId: '1:445883730465:ios:8296e1a1b451b58bdf3160',
    messagingSenderId: '445883730465',
    projectId: 'kazutxt-firebase-overvie-5de13',
    storageBucket: 'kazutxt-firebase-overvie-5de13.firebasestorage.app',
    androidClientId: '445883730465-0p3crjr96r56krc5b72r264evab2o0ai.apps.googleusercontent.com',
    iosClientId: '445883730465-vd7ahgd0p8n3ui3erji329ta3e1m42dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTeamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSw2n_4c4UFgZCC90H8wYPLYEoc59vlxI',
    appId: '1:445883730465:ios:8296e1a1b451b58bdf3160',
    messagingSenderId: '445883730465',
    projectId: 'kazutxt-firebase-overvie-5de13',
    storageBucket: 'kazutxt-firebase-overvie-5de13.firebasestorage.app',
    androidClientId: '445883730465-0p3crjr96r56krc5b72r264evab2o0ai.apps.googleusercontent.com',
    iosClientId: '445883730465-vd7ahgd0p8n3ui3erji329ta3e1m42dn.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTeamApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiPVelqL1hpMHclb4eHOcA3dJTdaaTQaI',
    appId: '1:445883730465:web:c763dd42536a7375df3160',
    messagingSenderId: '445883730465',
    projectId: 'kazutxt-firebase-overvie-5de13',
    authDomain: 'kazutxt-firebase-overvie-5de13.firebaseapp.com',
    storageBucket: 'kazutxt-firebase-overvie-5de13.firebasestorage.app',
    measurementId: 'G-S5HR9F4KFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNPsUJkTajtsfOhS4M7vFXwlauWBpaow8',
    appId: '1:445883730465:android:4967c4d2802e6994df3160',
    messagingSenderId: '445883730465',
    projectId: 'kazutxt-firebase-overvie-5de13',
    storageBucket: 'kazutxt-firebase-overvie-5de13.firebasestorage.app',
  );

}